### ISSUE TITLE
playerRot Reference

### ISSUE THREAD

**Issue by jeffnyman** [sumanvid97/FlappyBird-AI#1]
https://github.com/sumanvid97/FlappyBird-AI/blob/ef6cf34aa8f916b5f165703f7333829b29236434/flappy_rl.py#L325

Just checking: what is playerRot? I assume playerRotation. But how is that figured in here.

**Comment by sumanvid97** [comment]
Hi! 
This variable `playerRot` was there in the [original environment](https://github.com/sourabhv/FlapPyBird) which is actually an additional enhancement to make the bird rotate with some angular velocity, apart from just the translation. You can check [this code](https://github.com/sourabhv/FlapPyBird/blob/master/flappy.py) from the original pygame repo to know more about what `playerRot` has been used for.
In our context, this feature is redundant and would have contributed to the already huge training time. 
We intended to remove this entire part, however, might have missed out on deleting this one line.
Thanks for pointing it out. I'll update this.
